cabal-version:      3.0
name:               chatnega

-- The package version.
-- See the Haskell package versioning policy (PVP) for standards
-- guiding when and how versions should be incremented.
-- https://pvp.haskell.org
-- PVP summary:     +-+------- breaking API changes
--                  | | +----- non-breaking API additions
--                  | | | +--- code changes with no API change
version:            0.1.0.0

-- A short (one-line) description of the package.
-- synopsis:

-- A longer description of the package.
-- description:

-- The license under which the package is released.
license:            MIT

-- The file containing the license text.
license-file:       LICENSE

-- The package author(s).
author:             Erchius

-- An email address to which users can send suggestions, bug reports, and patches.
maintainer:         erchius_jzy@mail.ustc.edu.cn

-- A copyright notice.
-- copyright:
category:           Agent
build-type:         Simple

common warnings
    ghc-options: -Wall -Wno-name-shadowing -Wno-unused-do-bind

common depends
    build-depends:    base
                    , aeson
                    , text
                    , time
                    , bytestring
                    , url
                    , req
                    , vector
                    , transformers

common modules
    other-modules:    Agent.Types
                    , Agent.Network
                    , Agent.History
                    , Agent.State
    hs-source-dirs:   src

common languageversion
    default-language: GHC2021
    default-extensions:   OverloadedStrings
                        , ExistentialQuantification
                        , AllowAmbiguousTypes
                        , TypeApplications
                        , RankNTypes
                        , RecordWildCards
                        , OverloadedRecordDot
                        , DuplicateRecordFields
                        , DataKinds
                        , DeriveGeneric
                        , ImportQualifiedPost
                        , ScopedTypeVariables

executable chatnega
    import:  warnings
    import:  depends
    import:  modules
    import:  languageversion
    main-is: Main.hs

executable chatnega-test
    import: warnings
    import: depends
    import: languageversion
    main-is: ./src/Agent/Test.hs
