cabal-version: 3.0
name:          chatnega

-- The package version.
-- See the Haskell package versioning policy (PVP) for standards
-- guiding when and how versions should be incremented.
-- https://pvp.haskell.org
-- PVP summary:     +-+------- breaking API changes
--                  | | +----- non-breaking API additions
--                  | | | +--- code changes with no API change
version:       0.1.0.0

-- A short (one-line) description of the package.
-- synopsis:

-- A longer description of the package.
-- description:

-- The license under which the package is released.
license:       MIT

-- The file containing the license text.
license-file:  LICENSE

-- The package author(s).
author:        Erchius

-- An email address to which users can send suggestions, bug reports, and patches.
maintainer:    erchius_jzy@mail.ustc.edu.cn

-- A copyright notice.
-- copyright:
category:      Agent
build-type:    Simple

common warnings
    ghc-options: -Wall -Wno-name-shadowing -Wno-unused-do-bind

common depends
    build-depends:
        , aeson         ^>=2.2.3
        , base          ^>=4.20.0
        , bytestring    ^>=0.12.1
        , req           ^>=3.13.4
        , text          ^>=2.1.1
        , time          ^>=1.12.2
        , transformers  ^>=0.6.1
        , url           ^>=2.1.3
        , vector        ^>=0.13.2
        , mtl

common modules
    other-modules:
        Agent.History
        Agent.Network
        Agent.Types

    hs-source-dirs: src

common languageversion
    default-language:   GHC2021
    default-extensions:
        AllowAmbiguousTypes
        DataKinds
        DeriveGeneric
        DuplicateRecordFields
        ExistentialQuantification
        ImportQualifiedPost
        OverloadedRecordDot
        OverloadedStrings
        RankNTypes
        RecordWildCards
        ScopedTypeVariables
        TypeApplications

executable chatnega
    import:  warnings
    import:  depends
    import:  modules
    import:  languageversion
    main-is: Main.hs

executable chatnega-test
    import:  warnings
    import:  depends
    import:  languageversion
    main-is: ./src/Agent/Test.hs

library
    import:          warnings
    import:          depends
    import:          languageversion
    hs-source-dirs:  src
    exposed-modules:
        Agent.History
        Agent.Network
        Agent.Types
